{% set version = "2.3.4" %}

package:
  name: binwalk
  version: {{ version }}

source:
  # pypi version is... very old
  url: https://github.com/ReFirmLabs/binwalk/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 60416bfec2390cec76742ce942737df3e6585c933c2467932f59c21e002ba7a9
  patches:
    - 0000-setup-py-version.diff
    - 0001-extractor-is-zero.diff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - binwalk = binwalk.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  source_files:
    - testing/tests
  requires:
    - m2-grep  # [win]
    - nose
    - pip
    - pytest-cov
  imports:
    - binwalk
  commands:
    - pip check
    - binwalk --help
    - binwalk --help | grep -iE "Binwalk v{{ version.replace('.', '\.') }}"
    - cd testing/tests && pytest -vv --cov=binwalk --cov=branch --cov-report=term-missing:skip-covered -k "not firmware_zip" --cov-fail-under=57

about:
  home: https://github.com/ReFirmLabs/binwalk
  summary: Firmware analysis tool
  license: MIT
  license_file:
    - LICENSE
    - NOTICE.md
  doc_url: https://github.com/ReFirmLabs/binwalk/wiki

extra:
  recipe-maintainers:
    - bollwyvl
